#!/usr/bin/env python3
"""Generate wasm/src/src/wasm_jit_fuse_table.h (fused pair superinstructions).

Parses the RXJIT_K_* enum from wasm_jit_decode.h, models the per-kind
probability of a RandomX v1 program under rxjit_decode_for_interp's mapping,
ranks all pairs (A,B) by p(A)*p(B) (adjacent ops independent), excludes NOP,
CFROUND and EXIT, and emits ALL candidate pairs (RXJIT_FUSE_NMAX) in that
order. A module with fuse_n pairs uses the prefix [0, fuse_n), i.e. the top
fuse_n; RXJIT_FUSE_N_DEFAULT (the arm profile) keeps kinds within a u8.

Usage: python3 wasm/tools/gen_fuse_table.py
Re-run whenever the kind enum changes (a _Static_assert enforces it).
"""
import os, re
from fractions import Fraction as F

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src', 'src')
hdr = open(os.path.join(SRC, 'wasm_jit_decode.h')).read()
m = re.search(r'enum \{\s*RXJIT_K_NOP = 0,(.*?)RXJIT_K_COUNT', hdr, re.S)
names = ['NOP'] + re.findall(r'RXJIT_K_(\w+)\s*,', m.group(1))
K = len(names)
assert names[-1] == 'EXIT'

freq = dict(IADD_RS=16, IADD_M=7, ISUB_R=16, ISUB_M=7, IMUL_R=16, IMUL_M=4, IMULH_R=4, IMULH_M=1,
            ISMULH_R=4, ISMULH_M=1, IMUL_RCP=8, INEG_R=2, IXOR_R=15, IXOR_M=5, IROR_R=8, IROL_R=2,
            ISWAP_R=4, FSWAP_R=4, FADD_R=16, FADD_M=5, FSUB_R=16, FSUB_M=5, FSCAL_R=6, FMUL_R=32,
            FDIV_M=4, FSQRT_R=6, CBRANCH=25, CFROUND=1, ISTORE=16)
assert sum(freq.values()) == 256
p = {}
def add(n, w):
    assert n in names, n
    p[n] = p.get(n, 0) + w
e = F(1, 8)
L1, L2 = F(3, 4), F(1, 4)
for op, f in freq.items():
    f = F(f, 256)
    if op == 'IADD_RS':
        add('IADD_RS_DISPL', f * e); add('IADD_RS', f * (1 - e))
    elif op in ('IADD_M', 'ISUB_M', 'IMUL_M', 'IMULH_M', 'ISMULH_M', 'IXOR_M'):
        add(op + '_DIRECT', f * e); add(op + '_L1', f * (1 - e) * L1); add(op + '_L2', f * (1 - e) * L2)
    elif op in ('ISUB_R', 'IMUL_R', 'IXOR_R', 'IROR_R', 'IROL_R'):
        add(op + '_IMM', f * e); add(op, f * (1 - e))
    elif op == 'ISWAP_R':
        add('NOP', f * e); add('ISWAP_R', f * (1 - e))
    elif op == 'FSWAP_R':
        add('FSWAP_R_F', f / 2); add('FSWAP_R_E', f / 2)
    elif op in ('FADD_M', 'FSUB_M', 'FDIV_M'):
        add(op + '_L1', f * L1); add(op + '_L2', f * L2)
    elif op == 'ISTORE':
        add('ISTORE_L3', f * F(2, 16)); add('ISTORE_L1', f * F(14, 16) * L1); add('ISTORE_L2', f * F(14, 16) * L2)
    else:
        add(op, f)
assert sum(p.values()) == 1

N_DEFAULT = 200
EXC = {'NOP', 'CFROUND', 'EXIT'}
cand = [(a, b) for a in names for b in names if a not in EXC and b not in EXC and a in p and b in p]
cand.sort(key=lambda ab: (-p[ab[0]] * p[ab[1]], names.index(ab[0]), names.index(ab[1])))
pairs = cand
N = len(pairs)
assert K + N_DEFAULT <= 255
cov = lambda n: float(sum(p[a] * p[b] for a, b in pairs[:n]))

tab = [[0] * K for _ in range(K)]
for i, (a, b) in enumerate(pairs):
    tab[names.index(a)][names.index(b)] = K + i

out = []
out.append('// GENERATED by wasm/tools/gen_fuse_table.py -- do not edit.')
out.append('// Fused pair superinstructions: kind K+i runs record r as kind pairs[i][0],')
out.append('// then record r+1 as kind pairs[i][1], then advances ip by 32. All candidate')
out.append('// pairs, best first: a module with fuse_n pairs uses the prefix [0, fuse_n).')
out.append(f'// Pair coverage sum p(A)p(B): {cov(N_DEFAULT)*100:.1f}% at the default {N_DEFAULT}, '
           f'{cov(N)*100:.1f}% at all {N}.')
out.append('#pragma once')
out.append('#include <stdint.h>')
out.append('#include "wasm_jit_decode.h"')
out.append(f'#define RXJIT_FUSE_K {K}')
out.append(f'#define RXJIT_FUSE_NMAX {N}')
out.append(f'#define RXJIT_FUSE_N_DEFAULT {N_DEFAULT}')
out.append('_Static_assert(RXJIT_FUSE_K == RXJIT_K_COUNT, "regenerate wasm_jit_fuse_table.h");')
out.append('_Static_assert(RXJIT_FUSE_K + RXJIT_FUSE_N_DEFAULT <= 255, "the default keeps u8 kinds");')
out.append('static const uint8_t rxjit_fuse_pairs[RXJIT_FUSE_NMAX][2] = {')
for i, (a, b) in enumerate(pairs):
    out.append(f'\t{{RXJIT_K_{a}, RXJIT_K_{b}}}, // {K+i}: {float(p[a]*p[b])*256:.3f}/256')
out.append('};')
out.append('// [a][b] -> fused kind K+i (0 = none); fusable iff K+i < K+fuse_n')
out.append('static const uint16_t rxjit_fuse_tab[RXJIT_FUSE_K][RXJIT_FUSE_K] = {')
for a in range(K):
    out.append('\t{' + ','.join(str(v) for v in tab[a]) + '},')
out.append('};')
open(os.path.join(SRC, 'wasm_jit_fuse_table.h'), 'w').write('\n'.join(out) + '\n')
print(f'K={K} NMAX={N} pair coverage {cov(N_DEFAULT)*100:.1f}% at {N_DEFAULT}, {cov(N)*100:.1f}% at {N}')
